name: cloudrun-deploy
on:
  push:
    branches:
      - master

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2.1.3
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WF_PROVIDER }}'
          service_account: '${{ secrets.WF_SERVICE_ACCOUNT }}'
